/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-12-06 14:53:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layout.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.5.2.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-yui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-replace.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/Cabin_400.font.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/tabs.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.jqtransform.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.nivo.slider.pack.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/atooltip.jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page4\">\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("  <!--header -->\r\n");
      out.write("  <header>\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("      <h1>  </h1>\r\n");
      out.write("       <h1>&nbsp  </h1>\r\n");
      out.write("\t   <h1>&nbsp  </h1>\r\n");
      out.write("\t   <br/>\r\n");
      out.write("\t   \r\n");
      out.write("\t   <br/>\r\n");
      out.write("\t   <h1>&nbsp  </h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav>\r\n");
      out.write("    <form name=\"linkForm\" method=\"post\">\r\n");
      out.write("           <input type=\"hidden\"  class=\"input\"  name=\"viewType\" value=\"\"/>\r\n");
      out.write("                <ul id=\"menu\">\r\n");
      out.write("\t\t  <li    id=\"menu_active\"><a href=\"#\" onClick=\"performAction('home');\"><span><span>Search Courses</span></span></a></li>\r\n");
      out.write("\t\t   <li><a href=\"#\" onClick=\"performAction('managecourses');\"><span><span>Manage Courses</span></span></a></li>\r\n");
      out.write("\t\t   <li><a href=\"#\" onClick=\"performAction('viewassignments');\"><span><span>View Assignments</span></span></a></li>\r\n");
      out.write("\t\t   <li><a href=\"#\" onClick=\"performAction('viewgrades');\"><span><span>View Grades</span></span></a></li>\r\n");
      out.write("\t\t  <li ><a href=\"#\" onClick=\"performAction('services');\"><span><span>Service Requests</span></span></a></li>\r\n");
      out.write("        \t<!-- <li><a href=\"#\" onClick=\"performAction('viewprofile');\"><span><span>Manage Profile</span></span></a></li> -->\r\n");
      out.write("         <li class=\"end\"><a href=\"#\" onClick=\"logoutAction('logout');\"><span><span>Logout</span></span></a></li>\r\n");
      out.write("       \r\n");
      out.write("      </ul>\r\n");
      out.write("      </form>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    function logoutAction(viewType) {\r\n");
      out.write("    \t\r\n");
      out.write("    \tdocument.linkForm.viewType.value=viewType;\r\n");
      out.write("    \tdocument.linkForm.action = \"loginServlet\";\r\n");
      out.write("    \tdocument.linkForm.submit();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function performAction(viewType) {\r\n");
      out.write("    \tdocument.linkForm.viewType.value=viewType;\r\n");
      out.write("    \tdocument.linkForm.action = \"servicesServlet\";\r\n");
      out.write("    \tif(viewType=='viewprofile') {\r\n");
      out.write("    \t\tdocument.linkForm.action = \"profileServlet\";\r\n");
      out.write("    \t}\r\n");
      out.write("    \tdocument.linkForm.submit();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function enrollCourse(aptId) {\r\n");
      out.write("    \tdocument.ContactForm.viewType.value=\"enrollcourse\";\r\n");
      out.write("    \tdocument.ContactForm.selectedcourse.value=aptId;\r\n");
      out.write("    \tvar r = confirm(\"Are you sure to enroll ? \");\r\n");
      out.write("    \tif(r==true) {\r\n");
      out.write("    \t\tdocument.ContactForm.submit();\r\n");
      out.write("    \t}else {\r\n");
      out.write("    \t\treturn false;\r\n");
      out.write("    \t}\r\n");
      out.write("    \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  </header>\r\n");
      out.write("  <!-- / header -->\r\n");
      out.write("  <!--content -->\r\n");
      out.write("  <section id=\"content\">\r\n");
      out.write("    <div class=\"wrapper pad1\">\r\n");
      out.write("    \r\n");
      out.write(" <h3 class=\"pad_top1\">Search Courses</h3>\r\n");
      out.write("      <form name=\"ContactForm\" id=\"ContactForm\" action=\"servicesServlet\" method=\"post\"> \r\n");
      out.write("       <input type=\"hidden\"  class=\"input\"  name=\"viewType\" value=\"search\"/>\r\n");
      out.write("        <input type=\"hidden\"  class=\"input\"  name=\"selectedcourse\" value=\"\"/>\r\n");
      out.write("        <table width=\"50%\">\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <tr><td colspan=\"8\">&nbsp;</td></tr>\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("            <tr>\r\n");
      out.write("            <td colspan=\"2\"> \r\n");
      out.write("            ");
      if (_jspx_meth_core_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("                         \r\n");
      out.write("           <tr><td>&nbsp;</td></tr>\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("            <tr>\r\n");
      out.write("            <td colspan=\"2\"> \r\n");
      out.write("                   \r\n");
      out.write("            </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("                         \r\n");
      out.write("           <tr><td>&nbsp;</td></tr>\r\n");
      out.write("            \r\n");
      out.write("              <tr> <td>Department Name:</td>\r\n");
      out.write("            <td> <input type=\"text\" class=\"input\" name=\"deptname\"  value=\"\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("              <tr><td>&nbsp;</td></tr>\r\n");
      out.write("         <tr>     \r\n");
      out.write("        <td > Department Type : </td>\r\n");
      out.write("        <td >  <select name=\"dtype\" id=\"dtype\">\r\n");
      out.write("        <option value=\"select\">Select</option>\r\n");
      out.write("         <option value=\"Under Graduate\">Under Graduate</option>\r\n");
      out.write("        <option value=\"Graduate\" selected>Graduate</option>\r\n");
      out.write("        </select>  \r\n");
      out.write("                </td>\r\n");
      out.write("        \r\n");
      out.write("              </tr>\r\n");
      out.write("        \r\n");
      out.write("                 \r\n");
      out.write("        <tr><td>&nbsp;</td></tr>\r\n");
      out.write("          \r\n");
      out.write("         <tr>\r\n");
      out.write("        <td>Course Name</td>\r\n");
      out.write("        <td> <input type=\"text\"  class=\"input\"  name=\"cname1\" value=\"\"/></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr><td>&nbsp;</td></tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr>\r\n");
      out.write("        <td>Course Code : </td>\r\n");
      out.write("        <td> <input type=\"text\"  class=\"input\"  name=\"ccode1\"  value=\"\"/></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        \r\n");
      out.write("        <tr><td>&nbsp;</td></tr>\r\n");
      out.write("        <tr>\r\n");
      out.write("         <td> Availability </td>\r\n");
      out.write("        <td>  <select name=\"avail1\" id=\"avail1\">\r\n");
      out.write("        <option value=\"select\">Select</option>\r\n");
      out.write("         <option value=\"Spring\">Spring</option>\r\n");
      out.write("        <option value=\"Summer\">Summer</option>\r\n");
      out.write("        <option value=\"Fall\" selected>Fall</option>\r\n");
      out.write("        </select>  \r\n");
      out.write("                </td>\r\n");
      out.write("             </tr>   \r\n");
      out.write("             \r\n");
      out.write("                       <tr><td>&nbsp;</td></tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("\t\t\t\t\t<td  align=\"center\"><input type=\"submit\" value=\"Search\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <table width=\"100%\" >\r\n");
      out.write("        \r\n");
      out.write("        <tr><td>&nbsp;</td></tr>\r\n");
      out.write("        <tr><td>&nbsp;</td></tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td colspan=\"7\"> <h4>Course Details</h4> </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr><td>&nbsp;</td></tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("     <th>Course Name</th>\r\n");
      out.write("     <th>Course Code</th>\r\n");
      out.write("     <th>Professor</th>\r\n");
      out.write("     <th>Capacity</th>\r\n");
      out.write("     <th>Remaining</th>\r\n");
      out.write("     <th>Level</th>\r\n");
      out.write("     <th>Action</th>\r\n");
      out.write("      </tr> \r\n");
      out.write("      \r\n");
      out.write("      <tr><td colspan=\"7\">&nbsp;</td></tr> \r\n");
      out.write("    ");
      if (_jspx_meth_core_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("    \r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">Cufon.now();</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_core_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_core_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_core_005fif_005f0.setParent(null);
    // /home.jsp(104,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMsg}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_core_005fif_005f0 = _jspx_th_core_005fif_005f0.doStartTag();
    if (_jspx_eval_core_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("             <font color=\"red\">");
        if (_jspx_meth_core_005fout_005f0(_jspx_th_core_005fif_005f0, _jspx_page_context))
          return true;
        out.write("</font>\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_core_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_core_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_core_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_core_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_core_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_core_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f0);
    // /home.jsp(105,31) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_core_005fout_005f0 = _jspx_th_core_005fout_005f0.doStartTag();
    if (_jspx_th_core_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_core_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_core_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_core_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_core_005fforEach_005f0.setParent(null);
    // /home.jsp(190,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f0.setVar("course");
    // /home.jsp(190,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${departmentsList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int[] _jspx_push_body_count_core_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_core_005fforEach_005f0 = _jspx_th_core_005fforEach_005f0.doStartTag();
      if (_jspx_eval_core_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    <tr align=\"center\">\r\n");
          out.write("    <td>");
          if (_jspx_meth_core_005fout_005f1(_jspx_th_core_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f0))
            return true;
          out.write(" </td>\r\n");
          out.write("    <td>");
          if (_jspx_meth_core_005fout_005f2(_jspx_th_core_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f0))
            return true;
          out.write(" </td>\r\n");
          out.write("    <td>");
          if (_jspx_meth_core_005fout_005f3(_jspx_th_core_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f0))
            return true;
          out.write(" </td>\r\n");
          out.write("    <td>");
          if (_jspx_meth_core_005fout_005f4(_jspx_th_core_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f0))
            return true;
          out.write(" </td>\r\n");
          out.write("    <td>");
          if (_jspx_meth_core_005fout_005f5(_jspx_th_core_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f0))
            return true;
          out.write(" </td>\r\n");
          out.write("    <td>");
          if (_jspx_meth_core_005fout_005f6(_jspx_th_core_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f0))
            return true;
          out.write(" </td>\r\n");
          out.write("    <td><a href=\"#\"  onClick=\"enrollCourse('");
          if (_jspx_meth_core_005fout_005f7(_jspx_th_core_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_core_005fforEach_005f0))
            return true;
          out.write("');\">Enroll</a></td>\r\n");
          out.write("    </tr>\r\n");
          out.write("    \r\n");
          out.write("    ");
          int evalDoAfterBody = _jspx_th_core_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_core_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_core_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_core_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_core_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fcore_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_core_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_core_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_core_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_core_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_core_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f0);
    // /home.jsp(192,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.courseName}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_core_005fout_005f1 = _jspx_th_core_005fout_005f1.doStartTag();
    if (_jspx_th_core_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_core_005fout_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_core_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_core_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_core_005fout_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f0);
    // /home.jsp(193,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.courseCode}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_core_005fout_005f2 = _jspx_th_core_005fout_005f2.doStartTag();
    if (_jspx_th_core_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_core_005fout_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_core_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_core_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_core_005fout_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f0);
    // /home.jsp(194,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.professor}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_core_005fout_005f3 = _jspx_th_core_005fout_005f3.doStartTag();
    if (_jspx_th_core_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_core_005fout_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_core_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_core_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_core_005fout_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f0);
    // /home.jsp(195,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.capacity}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_core_005fout_005f4 = _jspx_th_core_005fout_005f4.doStartTag();
    if (_jspx_th_core_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_core_005fout_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_core_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_core_005fout_005f5.setPageContext(_jspx_page_context);
    _jspx_th_core_005fout_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f0);
    // /home.jsp(196,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.remaining}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_core_005fout_005f5 = _jspx_th_core_005fout_005f5.doStartTag();
    if (_jspx_th_core_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f5);
    return false;
  }

  private boolean _jspx_meth_core_005fout_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_core_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_core_005fout_005f6.setPageContext(_jspx_page_context);
    _jspx_th_core_005fout_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f0);
    // /home.jsp(197,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.type}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_core_005fout_005f6 = _jspx_th_core_005fout_005f6.doStartTag();
    if (_jspx_th_core_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f6);
    return false;
  }

  private boolean _jspx_meth_core_005fout_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_core_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_core_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_core_005fout_005f7.setPageContext(_jspx_page_context);
    _jspx_th_core_005fout_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fforEach_005f0);
    // /home.jsp(198,44) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${course.courseId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_core_005fout_005f7 = _jspx_th_core_005fout_005f7.doStartTag();
    if (_jspx_th_core_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f7);
    return false;
  }
}
