/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-12-06 14:55:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>Course Management System</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layout.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.5.2.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-yui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-replace.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/Cabin_400.font.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/tabs.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.jqtransform.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.nivo.slider.pack.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/atooltip.jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page4\">\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("  <!--header -->\r\n");
      out.write("    <header>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("      <h1>  </h1>\r\n");
      out.write("       <h1>&nbsp  </h1>\r\n");
      out.write("\t   <h1>&nbsp  </h1>\r\n");
      out.write("\t   <br/>\r\n");
      out.write("\t   \r\n");
      out.write("\t   <br/>\r\n");
      out.write("\t   <h1>&nbsp  </h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <nav>\r\n");
      out.write("        <form name=\"linkForm\" method=\"post\">\r\n");
      out.write("    <input type=\"hidden\"  class=\"input\"  name=\"viewType\" value=\"\"/>\r\n");
      out.write("\r\n");
      out.write("      </form>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    function performAction(viewType) {\r\n");
      out.write("    \tdocument.linkForm.viewType.value=viewType;\r\n");
      out.write("    \tdocument.linkForm.action = \"offersServlet\";\r\n");
      out.write("    \tdocument.linkForm.submit();\r\n");
      out.write("    }\r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("  </header>\r\n");
      out.write("  <!-- / header -->\r\n");
      out.write("  <!--content -->\r\n");
      out.write("  <section id=\"content\">\r\n");
      out.write("    <div class=\"wrapper pad1\" align=\"center\">\r\n");
      out.write("    \r\n");
      out.write(" <h3 class=\"pad_top1\">Login</h3>\r\n");
      out.write("        <form id=\"ContactForm\" action=\"loginServlet\" method=\"post\">\r\n");
      out.write("        <input type=\"hidden\"  class=\"input\"  name=\"viewType\" required=\"required\" value=\"login\"/>\r\n");
      out.write("        <table>\r\n");
      out.write("        \r\n");
      out.write("         <tr><td>&nbsp;</td></tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("            <td colspan=\"2\"> \r\n");
      out.write("            ");
      if (_jspx_meth_core_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            </td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr><td>&nbsp;</td></tr>\r\n");
      out.write("              \r\n");
      out.write("        <tr>\r\n");
      out.write("        <td>  Name: </td>\r\n");
      out.write("        <td> <input type=\"text\"  class=\"input\"  name=\"username\" required=\"required\" value=\"student11\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr><td>&nbsp;</td></tr>\r\n");
      out.write("            <tr> <td>Password:</td>\r\n");
      out.write("            <td> <input type=\"password\" class=\"input\" name=\"userpass\" required=\"required\" value=\"student11\"/></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              <tr><td>&nbsp;</td></tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" align=\"center\"><input type=\"submit\" value=\"Login\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr><td>&nbsp;</td></tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" align=\"center\">New User? Click <a href=\"register.jsp\">here</a> to register.</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr><td>&nbsp;</td></tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" align=\"center\"><a href=\"forgotpassword.jsp\">Forgot Password?</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("              </table>\r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <!--content end-->\r\n");
      out.write("  <!--footer -->\r\n");
      out.write("  <footer>\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!--footer end-->\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">Cufon.now();</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_core_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_core_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_core_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_core_005fif_005f0.setParent(null);
    // /login.jsp(70,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty errorMsg}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
    int _jspx_eval_core_005fif_005f0 = _jspx_th_core_005fif_005f0.doStartTag();
    if (_jspx_eval_core_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("             <font color=\"red\">");
        if (_jspx_meth_core_005fout_005f0(_jspx_th_core_005fif_005f0, _jspx_page_context))
          return true;
        out.write("</font>\r\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_core_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_core_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fif_0026_005ftest.reuse(_jspx_th_core_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_core_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_core_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_core_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_core_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_core_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_core_005fif_005f0);
    // /login.jsp(71,31) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${errorMsg}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_core_005fout_005f0 = _jspx_th_core_005fout_005f0.doStartTag();
    if (_jspx_th_core_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_core_005fout_005f0);
    return false;
  }
}
