/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.67
 * Generated at: 2016-12-06 14:55:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layout.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" media=\"all\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery-1.5.2.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-yui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/cufon-replace.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/Cabin_400.font.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/tabs.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.jqtransform.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.nivo.slider.pack.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/atooltip.jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"page4\">\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("  <!--header -->\r\n");
      out.write("  <header>\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("      <h1>  </h1>\r\n");
      out.write("       <h1>&nbsp  </h1>\r\n");
      out.write("\t   <h1>&nbsp  </h1>\r\n");
      out.write("\t   <br/>\r\n");
      out.write("\t   \r\n");
      out.write("\t   <br/>\r\n");
      out.write("\t   <h1>&nbsp  </h1>\r\n");
      out.write("    </div>\r\n");
      out.write("        <nav>\r\n");
      out.write("        <form name=\"linkForm\" method=\"post\">\r\n");
      out.write("    <input type=\"hidden\"  class=\"input\"  name=\"viewType\" value=\"\"/>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <ul id=\"menu\">\r\n");
      out.write("        <li id=\"menu_active\"><a href=\"login.jsp\"><span><span>Login</span></span></a></li>\r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("      </form>\r\n");
      out.write("    </nav>\r\n");
      out.write("    \r\n");
      out.write("  </header>\r\n");
      out.write("  <!-- / header -->\r\n");
      out.write("  <!--content -->\r\n");
      out.write("  <section id=\"content\">\r\n");
      out.write("    <div class=\"wrapper pad1\" align=\"center\">\r\n");
      out.write("    \r\n");
      out.write(" <h3 class=\"pad_top1\">New User Form</h3>\r\n");
      out.write("        <form id=\"ContactForm\" action=\"profileServlet\" method=\"post\">\r\n");
      out.write("        <input type=\"hidden\"  class=\"input\"  name=\"viewType\" required=\"required\" value=\"register\"/>\r\n");
      out.write("        <table align=\"center\">\r\n");
      out.write("        <tr>\r\n");
      out.write("        <td> User Name: </td>\r\n");
      out.write("        <td> <input type=\"text\"  class=\"input\"  name=\"username\" required=\"required\" value=\"student1\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr><td>&nbsp;</td></tr>\r\n");
      out.write("            <tr> <td>Password:</td>\r\n");
      out.write("            <td> <input type=\"password\" class=\"input\" name=\"userpass\" required=\"required\" value=\"student1\"/></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              \r\n");
      out.write("                   <tr><td>&nbsp;</td></tr>\r\n");
      out.write("              \r\n");
      out.write("        <tr>\r\n");
      out.write("        <td>  Security Question: </td>\r\n");
      out.write("        <td>  <select name=\"securityquestion\">\r\n");
      out.write("        <option value=\"1\">What is the name of your favorite teacher?</option>\r\n");
      out.write("        <option value=\"2\">What is the name of your pet?</option>\r\n");
      out.write("        <option value=\"3\">What is the name of your first employer?</option>\r\n");
      out.write("        <option value=\"4\">What is the name of your best friend?</option>        \r\n");
      out.write("        </select></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr><td>&nbsp;</td></tr>\r\n");
      out.write("            <tr> <td>Security Answer:</td>\r\n");
      out.write("            <td> <input type=\"password\" class=\"input\" name=\"securityanswer\" required=\"required\" value=\"student\"/></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              \r\n");
      out.write("         <tr><td>&nbsp;</td></tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("        <td> User Type  : </td>\r\n");
      out.write("        <td>  <select name=\"usertype\" id=\"usertype\">\r\n");
      out.write("         <option value=\"student\">Student</option>\r\n");
      out.write("        <option value=\"staff\">Staff</option>\r\n");
      out.write("        </select>  \r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("              <tr><td>&nbsp;</td></tr>\r\n");
      out.write("               <tr>\r\n");
      out.write("        <td>  First Name: </td>\r\n");
      out.write("        <td> <input type=\"text\"  class=\"input\"  name=\"firstname\" required=\"required\" value=\"student1\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr><td>&nbsp;</td></tr>\r\n");
      out.write("             <tr>\r\n");
      out.write("        <td>  Middle Name: </td>\r\n");
      out.write("        <td> <input type=\"text\"  class=\"input\"  name=\"middlename\" required=\"required\" value=\"student1\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr><td>&nbsp;</td></tr>  \r\n");
      out.write("             <tr>\r\n");
      out.write("        <td>  Last Name: </td>\r\n");
      out.write("        <td> <input type=\"text\"  class=\"input\"  name=\"lastname\" required=\"required\" value=\"student1\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr><td>&nbsp;</td></tr>\r\n");
      out.write("             <tr>\r\n");
      out.write("        <td>  Mobile Number: </td>\r\n");
      out.write("        <td> <input type=\"text\"  class=\"input\"  name=\"mobileno\" required=\"required\" value=\"8121689601\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("           \r\n");
      out.write("            <tr><td>&nbsp;</td></tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("        <td>  Email Id: </td>\r\n");
      out.write("        <td> <input type=\"text\"  class=\"input\"  name=\"emailid\" required=\"required\" value=\"customer1@gmail.com\"/></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <tr><td>&nbsp;</td></tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("        <td> Department : </td>\r\n");
      out.write("        <td>  <select name=\"deptname\" id=\"deptname\" >\r\n");
      out.write("         <option value=\"Computer Science\">Computer Science</option>\r\n");
      out.write("        <option value=\"Psychology\">Psychology</option>\r\n");
      out.write("        <option value=\"CIS\">CIS</option>\r\n");
      out.write("        <option value=\"Mechanical\">Mechanical</option>\r\n");
      out.write("        </select>  \r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("                      <tr><td>&nbsp;</td></tr>\r\n");
      out.write("              <tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\" align=\"center\"><input type=\"submit\" value=\"Register\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("              </table>\r\n");
      out.write("    </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </section>\r\n");
      out.write("  <!--content end-->\r\n");
      out.write("  <!--footer -->\r\n");
      out.write("  <footer>\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("     \r\n");
      out.write("    </div>\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!--footer end-->\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">Cufon.now();</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
